services:
  - type: web
    name: consumoapk
    env: php
    region: oregon
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y libpq-dev
      docker-php-ext-install pdo_pgsql pgsql
      composer install --optimize-autoloader --no-dev
      php artisan migrate --force
    startCommand: "php -S 0.0.0.0:$PORT -t public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://consumoapk-1.onrender.com/
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: mi-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mi-app-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mi-app-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mi-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mi-app-db
          property: password
